### ISSUE TITLE
REST should return address in plain format rather than hex format. 

### ISSUE THREAD

**Issue by AnthonyLaw** [symbol/catapult-rest#604]
Example:

`"beneficiaryAddress": "6862F5B548DCB21163C530B8CF0FEA2A2C227278B11C5C8F"` (hex format)

`"beneficiaryAddress": "NBRPLNKI3SZBCY6FGC4M6D7KFIWCE4TYWEOFZDY"` (plain format)

**Comment by rg911** [comment]
absolutely agree

**Comment by fboucquez** [comment]
I agree too. Some addresses are aliases so it would be the namespace Id/hex

**Comment by fboucquez** [comment]
Related

https://github.com/nemtech/symbol-openapi/issues/182

**Comment by zachamo** [comment]
Fully agreed.. Worked around this in Python with:

import base64

def hexToAddress(hexKey):
    return base64.b32encode(bytes.fromhex(hexKey)).decode("utf-8").replace("=","")

def addresstoHex(address):
    address.replace("-","")+"="
    return bytes.hex(base64.b32decode(address))
