### ISSUE TITLE
please include block timestamp and feeMultiplier in transaction returned by transactions/confirmed

### ISSUE THREAD

**Issue by Jaguar0625** [symbol/catapult-rest#637]
similar to  #636 but for transactions/confirmed endpoint

**Comment by fboucquez** [comment]
Is it possible to add the size to the transactions collection meta? It would be nice to be able to know that information and the effective fee (size*feeMultipler) without serializing the transaction (especially aggregate transactions where the inner transactions are stored in other entries).

I know this could require a data migration, but just a point to consider for the future.

**Comment by Jaguar0625** [comment]
size is already returned by rest afaik

**Comment by fboucquez** [comment]
Uff, yes, you are right. Please ignore my comment.

**Comment by fboucquez** [comment]
@Jaguar0625 , should inner transactions include blocks' timestamp and feeMultiplier in the meta too?

![image](https://user-images.githubusercontent.com/5390558/131697345-a2a829c6-eb21-4094-9007-acd4e600a3bb.png)

**Comment by Jaguar0625** [comment]
yes, i would think so
