### ISSUE TITLE
Unlock zeromq version and fix the missing dependency issue in the node alpine image

### ISSUE THREAD

**Issue by yilmazbahadir** [symbol/catapult-rest#657]
Currently, `zeromq`  dependency is locked to version `5.2.0` as the latest version `5.2.8` introduces some dependencies missing in the `node:12.18.1-alpine` image thus causing `rest` container to crash (err: segmentation fault).

We should be adding the missing dependencies to the dockerfile (using node-alpine image) and unlocking the `zeromq` version.

p.s. using node-ubuntu version could bring a memory overhead thus ideally should be avoided.

**Comment by gimre-xymcity** [comment]
imo it's the other way around: alpine versions should be avoided.
musl libc might introduce hard to track errors (i.e. there's no way to compile/run catapult-client using alpine images)

**Comment by yilmazbahadir** [comment]
The industry was shifting to alpine based images at the time for minimal image footprint thus less disk space needed and faster downloads, smaller attack surface since no additional baggage etc. and that was some time ago. 

After creating the issue, started to have a bit of research into resolution. 

As you mentioned seen a lot of issues, complaints regarding the musl-libc dependency, busy-box bugs, segfault errors, performance, etc. with the alpine based images and as you go adding dependencies needed, the image created will get fatter(which is reasonable). So if we are already using/depending on ubuntu-based images maybe there is really no gain on sticking to the alpine images, happy to go with ubuntu(and update the issue) if no objections, @fboucquez, @Jaguar0625 ?

**Comment by fboucquez** [comment]
I'm happy about going unbutu, catapult already uses ubuntu so if the same tag is used, the user is actually saving space. Rosetta for example also adopted ubuntu as the standard. 

Should we merge https://github.com/symbol/catapult-rest/pull/656 or update to the latest zeromq + ubuntu image?

**Comment by yilmazbahadir** [comment]
I'd vote for `update to the latest zeromq + ubuntu image`
